nama=input("nama kamu siapa: ")
age=int(input("berapa umurmu: "))
domisili=(input("masukan asal daerah: ")
tanggal=input("masukan tanggal lahir: ")
kelamin=input("masukan identitas kelamin anda: ")
pekerjaan=input("status pekerjaan anda: ")
rt=int(input("rt berapa: "))
rw=int(input("rw berapa: "))
desa=input("desa mana: ")
kecamatan=input("kecamatan apa: ")
agama=input("apa agamamu: ")
alamat=input("alamat mana")
WNI="WNI"
SLM="SEUMUR HIDUP"
print("=========================================")
print("=          PROVINSI JAWA TIMUR           ")
print("=           KABUPATEN JOS JIS            ")
print("=                                        ")
print("=NIK  : 9999999999999999                 ")
print("=                                        ")
print('NAMA :',nama,"                          ")
print("TEMPAT/TANGGAL LAHIR",domisili,tanggal,  )     
print('JENIS KELAMIN :',kelamin," GOL DARAH:-  ")
print('ALAMAT :',alamat,"                      ")
print('RT/RW : ',rt,"/",rw,"                   ")
print('KEL/DESA : ',desa,"                     ")
print('AGAMA : ',agama,"                       ")
print('STATUS PERKAWINAN : ',kecamatan,"       ")
print('PEKERJAAN : ',pekerjaan,"               ")
print('KEWARGANEGARAAN : ',WNI,"               ")
print('BERLAKU HINGGA : ',SLM,"                ")
print("")